// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace BlazorDemoML.Model
{
    public class ModelInput
    {
        [ColumnName("col0"), LoadColumn(0)]
        public string Text { get; set; }

        [ColumnName("Label"), LoadColumn(1)]
        public bool Label { get; set; }
    }
}
